'use client'
import "@styles/globals.css"
import { Inter } from "next/font/google"
import { MoralisProvider } from "react-moralis"
import { NotificationProvider } from "web3uikit"
const inter = Inter({ subsets: ["latin"] })

export const metadata = {
    title: "Smart Contract Lottery",
    description: "Generated by create next app",
}

export default function RootLayout({ children }) {
    return (
        <MoralisProvider initializeOnMount ={false}>
        <html lang="en">
            <NotificationProvider>
            <body className={inter.className}>{children}</body>
            </NotificationProvider>
        </html>
        </MoralisProvider>
    )
}
